### ISSUE TITLE
任务无法选择+随机任务填充问题+时间貌似是错的？

### ISSUE THREAD

**Issue by 150BigDream** [Albert-W/Week-plan#1]
1. 我猜测日期下面那一栏是时间，上面横着一栏是日期。我尝试使用的时候是6.6，上面日期就是错的
2. 随机填充任务的地方很奇怪。不懂是不是我没理解到这个功能的用途
3. 不管在哪一天底下选择任务都是空白的，没有办法可以选

**总结：**可能是我不会用吧，感觉目前并没有办法使用。期待你的更新。

最后，图片没有办法上传。

**Comment by Albert-W** [comment]
已经更新到v1.5.0, 请尝试。
