### ISSUE TITLE
不管哪一个版本（1.4、1.6），打开来都是5月18-24的那一周

### ISSUE THREAD

**Issue by 150BigDream** [Albert-W/Week-plan#2]
不管哪一个版本，打开来都是5月18-24的那一周，需要自己手动修改日期才可以使用。
以及，请教作者一个问题，用新版本的话，原来的数据貌似是不能自己迁移过去的。请问你是怎么做的呢？

**Comment by Albert-W** [comment]
1.6 的日期也不能自动更新？
可以截图给我看一下吗？
如果切换新版本，可以直接把旧的数据复制过新的表格，表头不变就可以。

**Comment by 150BigDream** [comment]
这是重新下载的，仍然是这个日期。habits的日期就是对的。

summary有两个date



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Albert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 晚上11:39
收件人:&nbsp;"Albert-W/Week-plan"<Week-plan@noreply.github.com&gt;;
抄送:&nbsp;"2316624245"<2316624245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Albert-W/Week-plan] 不管哪一个版本（1.4、1.6），打开来都是5月18-24的那一周 (#2)





 
1.6 的日期也不能自动更新？
 可以截图给我看一下吗？
 如果切换新版本，可以直接把旧的数据复制过新的表格，表头不变就可以。

**Comment by Albert-W** [comment]
你好。我需要看到截图才知道怎么回事。 因为我自己的电脑上没有这个问题。

**Comment by Albert-W** [comment]
建议使用最新版v1.7.2
